# Generated by Django 3.0.3 on 2021-03-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('contact_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact')),
            ],
        ),
    ]
