# Generated by Django 3.0.3 on 2021-03-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
