# Generated by Django 3.0.3 on 2021-03-30 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0044_auto_20210313_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_b_friends', to=settings.AUTH_USER_MODEL)),
                ('friend_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_a_friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('friend_a', 'friend_b')},
            },
        ),
    ]
