# Generated by Django 3.0.3 on 2021-04-01 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0045_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requested', to=settings.AUTH_USER_MODEL)),
                ('requesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requesting', 'requested')},
            },
        ),
    ]
