# Generated by Django 3.0.3 on 2021-04-01 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
