name: Deploy

on:
  push:
    branches:
      - heroku_ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build Docker image
        run: docker build -f docker/Dockerfile.dev -t test-app-mfaria .
      - name: Rename image and push image to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker tag test-app-mfaria registry.heroku.com/test-app-mfaria/web
          docker push registry.heroku.com/test-app-mfaria/web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a test-app-mfaria web
